'use strict';
const VARIANTS=[
{id:'01',slug:'dawn-workshop',name:'朝の塗師蔵',kana:'あさの ぬしぐら',kicker:'写実案 01',subtitle:'朝の斜光が、黒漆のわずかな刷毛目だけを拾う。',process:'木地から、百二十四の手へ。',style:'暖色写実・深い奥行き',layout:'left',accent:'#d39a4d',ink:'#f7f0e5',panel:'rgba(22,15,10,.78)',button:'#98331f'},
{id:'02',slug:'rain-machiya',name:'雨の町家',kana:'あめの まちや',kicker:'湿度案 02',subtitle:'雨音の向こうで、漆は急がず、湿り気の中で固まる。',process:'乾かすのではなく、待って固める。',style:'青灰写実・雨天拡散光',layout:'right',accent:'#93b8c5',ink:'#ecf2f2',panel:'rgba(12,26,31,.80)',button:'#315d68'},
{id:'03',slug:'vermilion-hearth',name:'炉端の朱',kana:'ろばたの しゅ',kicker:'対比案 03',subtitle:'低い炉火の反射が、朱漆の厚みと曲率をあらわにする。',process:'火は光。硬化は、別の湿った部屋で。',style:'朱・炭・低い炉火',layout:'left',accent:'#f06b3e',ink:'#fff0e7',panel:'rgba(29,10,7,.82)',button:'#b52a16'},
{id:'04',slug:'snow-light',name:'雪明かり',kana:'ゆきあかり',kicker:'静謐案 04',subtitle:'北窓と雪面の反射だけで、黒い椀の輪郭を読む。',process:'静かな光ほど、塗りの差を隠さない。',style:'低彩度写実・冷たい面光',layout:'right',accent:'#d9e6e3',ink:'#f2f4ef',panel:'rgba(24,31,32,.74)',button:'#4d5f61'},
{id:'05',slug:'chinkin-beam',name:'沈金・一条の光',kana:'ちんきん・いちじょうの ひかり',kicker:'接写案 05',subtitle:'彫った溝だけが漆を抱き、金を残す。その因果を一画面に。',process:'黄色い線ではなく、光を返す金の溝。',style:'超接写・硬い一灯',layout:'compact',accent:'#d4aa47',ink:'#f3ead5',panel:'rgba(10,9,7,.84)',button:'#6e5420'},
{id:'06',slug:'makie-dust',name:'蒔絵の星屑',kana:'まきえの ほしくず',kicker:'粒子案 06',subtitle:'金粉は空中で光るのではない。半乾きの漆だけが受け止める。',process:'蒔く、寄せる、固める、磨く。',style:'暗褐色マクロ・金粉',layout:'right',accent:'#d8b66b',ink:'#f6edda',panel:'rgba(22,16,12,.82)',button:'#7b5c26'},
{id:'07',slug:'noto-calm',name:'能登の朝凪',kana:'のとの あさなぎ',kicker:'土地案 07',subtitle:'海から届く淡い光の下で、工芸と土地の距離をなくす。',process:'木と漆と手が、輪島で出会う。',style:'海辺写実・広い遠景',layout:'bottom',accent:'#e0b15c',ink:'#f4efe5',panel:'rgba(17,31,33,.72)',button:'#386c72'},
{id:'08',slug:'layers-124',name:'百二十四の層',kana:'ひゃくにじゅうよんの そう',kicker:'断面案 08',subtitle:'完成すると見えなくなる、木・布・地の粉・漆を開いて見せる。',process:'重ねるたび、研いで形を取り戻す。',style:'実物断面模型・粗密差',layout:'left',accent:'#c98950',ink:'#f1e8da',panel:'rgba(31,24,18,.80)',button:'#7f4028'},
{id:'09',slug:'white-gallery',name:'白い展示室',kana:'しろい てんじしつ',kicker:'形態案 09',subtitle:'装飾を引き算し、接地、厚み、合口、シルエットだけを残す。',process:'美しさを、構造から見る。',style:'正投影・美術館の面光',layout:'bottom',accent:'#8e2018',ink:'#26231f',panel:'rgba(246,244,238,.84)',button:'#8e2018'},
{id:'10',slug:'ink-lacquer',name:'墨と漆',kana:'すみと うるし',kicker:'質感案 10',subtitle:'紙は光を呑み、墨は滲み、漆だけが窓を映す。',process:'同じ黒でも、材質は同じではない。',style:'水墨的立体・生成紙',layout:'right',accent:'#9a3c28',ink:'#25221e',panel:'rgba(225,215,196,.78)',button:'#3f332a'},
{id:'11',slug:'woodblock',name:'輪島の木版色',kana:'わじまの もくはんいろ',kicker:'版画案 11',subtitle:'藍、黄土、朱。小さな画面でも形が崩れない三段階の陰影。',process:'輪郭は強く、道具の意味は正確に。',style:'木版色・三段階陰影',layout:'left',accent:'#e3ad43',ink:'#f7ead0',panel:'rgba(15,39,49,.82)',button:'#a64024'},
{id:'12',slug:'craft-town',name:'小さな職人町',kana:'ちいさな しょくにんまち',kicker:'分業案 12',subtitle:'一つの椀が、木地師、塗師、加飾師の工房を渡っていく。',process:'百二十四の手は、一人の手ではない。',style:'俯瞰箱庭・工程の地理',layout:'compact',accent:'#de8a45',ink:'#fff2dc',panel:'rgba(41,28,20,.78)',button:'#9c4c29'},
{id:'13',slug:'bowl-blueprint',name:'椀の設計図',kana:'わんの せっけいず',kicker:'構造案 13',subtitle:'径十四・一センチ、高さ九センチ。形を数字と断面で確かめる。',process:'外側だけでなく、内面と高台まで。',style:'非発光ブループリント',layout:'technical',accent:'#8fd0d2',ink:'#d7eeee',panel:'rgba(4,34,43,.80)',button:'#18596b'},
{id:'14',slug:'palm-workshop',name:'手のひら工房',kana:'てのひら こうぼう',kicker:'幼児視点案 14',subtitle:'四歳の目線までカメラを下げ、最初に触る道具を大きく置く。',process:'小さな手で、ほんものの動きを。',style:'明るい写実・低い目線',layout:'left',accent:'#ff8a63',ink:'#fff7eb',panel:'rgba(52,31,18,.78)',button:'#c64527'},
{id:'15',slug:'night-furo',name:'夜の塗師風呂',kana:'よるの ぬしぶろ',kicker:'硬化案 15',subtitle:'暗い陰室、湿った杉板、ゆっくり回る椀。待つ工程を主役に。',process:'温度二十度、湿度八十パーセントの目安。',style:'緑黒・湿潤室・弱い作業灯',layout:'right',accent:'#9eb69a',ink:'#e7eee4',panel:'rgba(11,24,18,.84)',button:'#365341'}
];
